[package]
name = "sf-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/tools/*",
]

[dependencies]

[dependencies.windows]
version = "0.48.0"
features = [
    "implement",
    "Win32_Foundation",
]
